# numpy basics

In [24]:
import numpy as np

In [25]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [26]:
print(np.__version__)
print(type(arr))

1.24.4
<class 'numpy.ndarray'>


In [27]:
#2d
twoD = np.array([[1,2,3], [4,5,6]])

print(twoD)
print(twoD.ndim)

[[1 2 3]
 [4 5 6]]
2


In [28]:
# [ count is the dimension :)
#  3-d means [d1, d2, element]
#  it is kinda a tree
threeD = np.array([
                   [[1,2,3], [4,5,6]],    #0 dimension has 2 dimension = three dimension
                   [[7,8,9], [10,11,12]]
                   ])

print(threeD)
print(threeD.ndim)
print(threeD[0,1,1])
print(threeD[0][1][1])  #same as above!

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
5
5


## indexing

In [29]:
print(arr[0])
print(twoD[0])
print(twoD[1][2])
print(twoD[1:])

1
[1 2 3]
6
[[4 5 6]]


## slicing

In [30]:
# [index : index - excluded]
print(arr[0:2])
print(twoD[0:])
print(twoD[0:1])
print(twoD[0][0:2])
print(twoD[0:2,1])  #both rows, only 2nd elements
print(twoD[:,1:3])  #both rows, only 2nd & 3rd elements, 2-d nparray

[1 2]
[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[1 2]
[2 5]
[[2 3]
 [5 6]]


## types

In [31]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [32]:
arrString = np.array(['apple', 'orange', 'berry'])
arrIntAsString = np.array([1, 2, 3], dtype='S')

print(arrString.dtype)
print(arrIntAsString.dtype)

<U6
|S1


In [33]:
# astype, copy the array, then converts!

arrIntFromString = arrIntAsString.astype(dtype='i8')

print(arrIntFromString)
print(arrIntFromString.dtype)

[1 2 3]
int64


In [34]:
arrBool = arrIntAsString.astype(dtype=bool)

print(arrBool)

[ True  True  True]


## copy

In [46]:
original = np.array([2, 4, 1, 6, 83, 10])

x = original.copy()
y = original.view()

original[0] = 20

print(original)
print(x)   #copy - as a new array
print(y)   #view - bound to the original

print(x.base)   #does it own the original
print(y.base)

[20  4  1  6 83 10]
[ 2  4  1  6 83 10]
[20  4  1  6 83 10]
None
[20  4  1  6 83 10]


In [47]:
print(original.shape)

(6,)


## reshaping (increasing the dimension)

In [50]:
# original is 1-d and 6 elements

print(original.size)    # 6 elements

originalReshaped = original.reshape(2, 3)   # (2 * 3) = 6 !!!

print(originalReshaped)     # returns a view (the original!!)
print(originalReshaped.shape)

6
[[20  4  1]
 [ 6 83 10]]
(2, 3)


## flatting (decreasing the dimension to 1D !)

In [57]:
#
print(twoD)  # 2-d array

twoDFlat = twoD.reshape(-1)  # make it 1-d

print(twoDFlat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [66]:
print(arr.shape)
print(twoD.shape)
print(threeD.shape)

# (x, y, z)
# x * y * z = total => means element count
# x, y, z count is 3 => means 3-d


(5,)
(2, 3)
(2, 2, 3)


## iteration

In [73]:
print(arr)

for i in arr:  # kinda foreach
    print(i)

[1 2 3 4 5]
1
2
3
4
5


In [68]:
print(twoD)

for x in twoD:
    for y in x:
        print(y)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [75]:
print(threeD)

for x in threeD:
    for y in x:
        for z in y:
            print(z)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [74]:
# more optimized way! esp. for N-d arrays
for x in np.nditer(threeD):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## enumeration (index, value)

In [80]:
# enumeration (index, value)

for idx, x in np.ndenumerate(arr):
    print(idx[0], '-' ,x)


0 - 1
1 - 2
2 - 3
3 - 4
4 - 5
