# numpy basics

In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
print(np.__version__)
print(type(arr))

1.24.4
<class 'numpy.ndarray'>


In [10]:
#2d
twoD = np.array([[1,2,3], [4,5,6]])

print(twoD)
print(twoD.ndim)

[[1 2 3]
 [4 5 6]]
2


In [38]:
# [ count is the dimension :)
#  3-d means [d1, d2, element]
#  it is kinda a tree
threeD = np.array([
                   [[1,2,3], [4,5,6]],    #0 dimension has 2 dimension = three dimension
                   [[7,8,9], [10,11,12]]
                   ])

print(threeD)
print(threeD.ndim)
print(threeD[0,1,1])
print(threeD[0][1][1])  #same as above!

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
5
5


## indexing

In [30]:
print(arr[0])
print(twoD[0])
print(twoD[1][2])
print(twoD[1:])

1
[1 2 3]
6
[[4 5 6]]


## slicing

In [50]:
# [index : index - excluded]
print(arr[0:2])
print(twoD[0:])
print(twoD[0:1])
print(twoD[0][0:2])
print(twoD[0:2,1])  #both rows, only 2nd elements
print(twoD[:,1:3])  #both rows, only 2nd & 3rd elements, 2-d nparray

[1 2]
[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[1 2]
[2 5]
[[2 3]
 [5 6]]


## types

In [52]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [55]:
arrString = np.array(['apple', 'orange', 'berry'])
arrIntAsString = np.array([1, 2, 3], dtype='S')

print(arrString.dtype)
print(arrIntAsString.dtype)

<U6
|S1


In [57]:
# astype, copy the array, then converts!

arrIntFromString = arrIntAsString.astype(dtype='i8')

print(arrIntFromString)
print(arrIntFromString.dtype)

[1 2 3]
int64


In [61]:
arrBool = arrIntAsString.astype(dtype=bool)

print(arrBool)

[ True  True  True]


## copy