# numpy basics

In [24]:
import numpy as np

In [25]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [26]:
print(np.__version__)
print(type(arr))

1.24.4
<class 'numpy.ndarray'>


In [27]:
#2d
twoD = np.array([[1,2,3], [4,5,6]])

print(twoD)
print(twoD.ndim)

[[1 2 3]
 [4 5 6]]
2


In [28]:
# [ count is the dimension :)
#  3-d means [d1, d2, element]
#  it is kinda a tree
threeD = np.array([
                   [[1,2,3], [4,5,6]],    #0 dimension has 2 dimension = three dimension
                   [[7,8,9], [10,11,12]]
                   ])

print(threeD)
print(threeD.ndim)
print(threeD[0,1,1])
print(threeD[0][1][1])  #same as above!

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
5
5


## indexing

In [29]:
print(arr[0])
print(twoD[0])
print(twoD[1][2])
print(twoD[1:])

1
[1 2 3]
6
[[4 5 6]]


## slicing

In [30]:
# [index : index - excluded]
print(arr[0:2])
print(twoD[0:])
print(twoD[0:1])
print(twoD[0][0:2])
print(twoD[0:2,1])  #both rows, only 2nd elements
print(twoD[:,1:3])  #both rows, only 2nd & 3rd elements, 2-d nparray

[1 2]
[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[1 2]
[2 5]
[[2 3]
 [5 6]]


## types

In [31]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [32]:
arrString = np.array(['apple', 'orange', 'berry'])
arrIntAsString = np.array([1, 2, 3], dtype='S')

print(arrString.dtype)
print(arrIntAsString.dtype)

<U6
|S1


In [33]:
# astype, copy the array, then converts!

arrIntFromString = arrIntAsString.astype(dtype='i8')

print(arrIntFromString)
print(arrIntFromString.dtype)

[1 2 3]
int64


In [34]:
arrBool = arrIntAsString.astype(dtype=bool)

print(arrBool)

[ True  True  True]


## copy

In [46]:
original = np.array([2, 4, 1, 6, 83, 10])

x = original.copy()
y = original.view()

original[0] = 20

print(original)
print(x)   #copy - as a new array
print(y)   #view - bound to the original

print(x.base)   #does it own the original
print(y.base)

[20  4  1  6 83 10]
[ 2  4  1  6 83 10]
[20  4  1  6 83 10]
None
[20  4  1  6 83 10]


In [47]:
print(original.shape)

(6,)


## reshaping (increasing the dimension)

In [50]:
# original is 1-d and 6 elements

print(original.size)    # 6 elements

originalReshaped = original.reshape(2, 3)   # (2 * 3) = 6 !!!

print(originalReshaped)     # returns a view (the original!!)
print(originalReshaped.shape)

6
[[20  4  1]
 [ 6 83 10]]
(2, 3)


## flatting (decreasing the dimension to 1D !)

In [57]:
#
print(twoD)  # 2-d array

twoDFlat = twoD.reshape(-1)  # make it 1-d

print(twoDFlat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [66]:
print(arr.shape)
print(twoD.shape)
print(threeD.shape)

# (x, y, z)
# x * y * z = total => means element count
# x, y, z count is 3 => means 3-d


(5,)
(2, 3)
(2, 2, 3)


## iteration

In [73]:
print(arr)

for i in arr:  # kinda foreach
    print(i)

[1 2 3 4 5]
1
2
3
4
5


In [68]:
print(twoD)

for x in twoD:
    for y in x:
        print(y)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [75]:
print(threeD)

for x in threeD:
    for y in x:
        for z in y:
            print(z)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [74]:
# more optimized way! esp. for N-d arrays
for x in np.nditer(threeD):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## enumeration (index, value)

In [84]:
# enumeration (index, value)

for idx, x in np.ndenumerate(arr):
    print(idx, '-' , x)


(0,) - 1
(1,) - 2
(2,) - 3
(3,) - 4
(4,) - 5


In [88]:
for idx, x in np.ndenumerate(twoD):
    print(idx, '-' , x)

(0, 0) - 1
(0, 1) - 2
(0, 2) - 3
(1, 0) - 4
(1, 1) - 5
(1, 2) - 6


## join _by axis_ or stack

In [127]:
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])

j = np.concatenate((x1, x2), axis=0)  #1 dim, max_axis=1 !
J = np.hstack((x1, x2))

print(j)
print(J)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [131]:
t1 = np.array([[1, 2],
               [3, 4]])    #shape => (2,2)
t2 = np.array([[5, 6],
               [7, 8]])

j1 = np.concatenate((t1, t2), axis=0)  #vertical
J1 = np.vstack((t1, t2))

j2 = np.concatenate((t1, t2), axis=1)  #horizontal
J2 = np.hstack((t1, t2))

print(j1); print(J1)
print(j2); print(J2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [123]:
k1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]])
k2 = np.array([[[19, 20, 21], [22, 23, 24], [25, 26, 27], [28, 29, 130], [31, 32, 33], [34, 35, 36]]])

# k-shape => (1,6,3)

jX =  np.concatenate((k1, k2), axis=0) #vertical   = .vstack(
jY =  np.concatenate((k1, k2), axis=1) #horizontal = .hstack(
jZ =  np.concatenate((k1, k2), axis=2) #sliced     = .dstack(


In [116]:
print(jX.shape)

print(jX)

(2, 6, 3)
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 10  11  12]
  [ 13  14  15]
  [ 16  17  18]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]
  [ 28  29 130]
  [ 31  32  33]
  [ 34  35  36]]]


In [119]:
print(jY.shape)
print(jY)

(1, 12, 3)
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 10  11  12]
  [ 13  14  15]
  [ 16  17  18]
  [ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]
  [ 28  29 130]
  [ 31  32  33]
  [ 34  35  36]]]


In [118]:
print(jZ.shape)
print(jZ)

(1, 6, 6)
[[[  1   2   3  19  20  21]
  [  4   5   6  22  23  24]
  [  7   8   9  25  26  27]
  [ 10  11  12  28  29 130]
  [ 13  14  15  31  32  33]
  [ 16  17  18  34  35  36]]]


## split