## numpy basics  _random_

In [1]:
from numpy import random


In [26]:
i = random.randint(0, 10, size=10)    # int, b/w 0 to 10, 100 integer random number
i2 = random.randint(0, 10, size=(5, 3)) # 2d array

print(i)
print(i2)

[9 2 4 7 4 9 4 7 7 7]
[[3 9 7]
 [9 6 3]
 [5 8 2]
 [5 8 8]
 [1 4 2]]


In [34]:
f = random.random(size=4)            # float b/w 0 to 1, and 100 random number
f2 = random.random(size=(3, 3))      # 2d
f3 = random.random(size=(1, 2, 3))   # 3d

print(f)
print(f2)
print(f3)

[0.77019296 0.35277896 0.07771439 0.60381557]
[[0.56257314 0.67657711 0.59985862]
 [0.83137285 0.3964514  0.89692894]
 [0.94247813 0.8496094  0.96413275]]
[[[0.94903107 0.39567895 0.0083502 ]
  [0.46140246 0.75542094 0.01910521]]]


In [35]:
k = random.choice([3, 4, 5], size=(2,2))

print(k)

[[4 3]
 [5 5]]
