## numpy basics  _random_

In [43]:
import numpy as np


In [46]:
# leverage generators.
# np.random.... is the old style!!

# i = random.randint(0, 10, size=10)    # old way
i = np.random.default_rng(100).integers(low=0, high=10, size=10)
i2 = np.random.default_rng(100).integers(0, 10, size=(5, 3)) # 2d array

print(i)
print(i2)

[7 8 1 5 0 2 4 0 5 9]
[[7 8 1]
 [5 0 2]
 [4 0 5]
 [9 9 5]
 [4 7 9]]


In [48]:
f = np.random.default_rng(100).random(size=4)            # float b/w 0 to 1, and 100 random number
f2 = np.random.default_rng(100).random(size=(3, 3))      # 2d
f3 = np.random.default_rng(100).random(size=(1, 2, 3))   # 3d

print(f)
print(f2)
print(f3)

[0.83498163 0.59655403 0.28886324 0.04295157]
[[0.83498163 0.59655403 0.28886324]
 [0.04295157 0.9736544  0.5964717 ]
 [0.79026316 0.91033938 0.68815445]]
[[[0.83498163 0.59655403 0.28886324]
  [0.04295157 0.9736544  0.5964717 ]]]


In [49]:
k = np.random.default_rng(10).choice([3, 4, 5], size=(2,2))

print(k)

[[5 5]
 [3 3]]
