## numpy basics  _random_

- use random generators
- then, use random/integers/choice or distributions !

In [43]:
import numpy as np


In [46]:
# leverage generators.
# np.random.... is the old style!!

# i = random.randint(0, 10, size=10)    # old way
i = np.random.default_rng(100).integers(low=0, high=10, size=10)
i2 = np.random.default_rng(100).integers(0, 10, size=(5, 3)) # 2d array

print(i)
print(i2)

[7 8 1 5 0 2 4 0 5 9]
[[7 8 1]
 [5 0 2]
 [4 0 5]
 [9 9 5]
 [4 7 9]]


In [50]:
f = np.random.default_rng(100).random(size=4)            # float b/w 0 to 1, and 100 random number
# f2 = np.random.default_rng(100).random(size=(3, 3))      # 2d
# f3 = np.random.default_rng(100).random(size=(1, 2, 3))   # 3d

print(f)

[0.83498163 0.59655403 0.28886324 0.04295157]


In [52]:
k = np.random.default_rng(10).choice([3, 4, 5, 6, 7, 8], size=(2,2))

print(k)

[[7 8]
 [4 4]]


In [72]:
# shuffle
# changes the original array !
x = [1, 2, 3, 4, 5, 6]

np.random.default_rng(seed=7).shuffle(x, axis=0)
#seed, guarantees the result won't change after a shuffle !

x

[6, 3, 1, 5, 2, 4]

In [74]:
# permutation
# returns a new array

z = np.random.default_rng(5).permutation(x, axis=0)

z

array([3, 2, 1, 5, 4, 6])