In [1]:
import numpy as np


### element-of ...
- multiply, sum, add, power, divide etc... is a easy way doing some operations on arrays
instead of for-loop ! so, shape must be same !

### product of ...
- but matrix operation such as matmul, differs from that !!!!

In [4]:
x = np.array([1, 2, 3])
y = np.array([10,20,30])

k = np.multiply(x, y)
z = np.matmul(x, y)

print(k)
print(z)   #matmul characteristic differs from multiplication of matrix's in some cases!

[10 40 90]
140


In [22]:
x = np.random.default_rng(10).choice([1, 2, 3, 4, 5], size=(2,3))
y = np.random.default_rng(10).choice([1, 2, 3, 4, 5], size=(3,3))

print(x)
print(y)

result = np.matmul(x, y)    # expects x(n,3) and y(3,m) = result(n, m)
# kkk = np.multiply(x,y)    # expects same shape! x(2,3) and y(2,3)

print("result \n", result)

[[4 5 2]
 [2 4 5]]
[[4 5 2]
 [2 4 5]
 [3 1 5]]
result 
 [[32 42 43]
 [31 31 49]]
