In [1]:
import numpy as np


### element-of ...
- multiply, sum, add, power, divide etc... is a easy way doing some operations on arrays
instead of for-loop ! so, shape must be same !

### product of ...
- but matrix operation such as matmul, differs from that !!!!

In [4]:
x = np.array([1, 2, 3])
y = np.array([10,20,30])

k = np.multiply(x, y)
z = np.matmul(x, y)

print(k)
print(z)   #matmul characteristic differs from multiplication of matrix's in some cases!

[10 40 90]
140


In [23]:
# the difference

x = np.random.default_rng(10).choice([1, 2, 3, 4, 5], size=(2,3))
y = np.random.default_rng(10).choice([1, 2, 3, 4, 5], size=(3,3))

print(x)
print(y)

result = np.matmul(x, y)    # expects x(n,3) and y(3,m) = result(n, m)
# kkk = np.multiply(x,y)    # expects same shape! x(2,3) and y(2,3)

print("result \n", result)

[[4 5 2]
 [2 4 5]]
[[4 5 2]
 [2 4 5]
 [3 1 5]]
result 
 [[32 42 43]
 [31 31 49]]


In [47]:
# some functions

x = np.random.default_rng(10).random(size=10, dtype='f')
x = np.multiply(x, 10)

x = np.round(x, decimals=2)   #rounds
y = np.trunc(x)               #cuts

print("x", x)
print("y", y)

x [7.77 9.56 2.64 2.08 7.93 8.28 5.15 1.49 8.33 5.13]
y [7. 9. 2. 2. 7. 8. 5. 1. 8. 5.]


In [53]:
# range, [start, stop) with ant step float/int

x = np.arange(start=1, stop=100, step=3)

print('x', x)


x [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
