## numpy - _transformation 2-d for ML_

- x, y to dataset
- dataset to x, y


In [1]:
import numpy as np

In [9]:
# generate x, y
# then combine as dataset

#think features as, (10 row, 3 features)
#       a b c
#   r1
#   r2
#
#   rn
#think labels as the target, (10 row, )
features = np.random.default_rng(10).integers(low=0, high=50, size=(10, 3))
labels = np.random.default_rng(10).integers(low=50, high=100, size=(10, ))

print("features", features, features.shape)
print("labels", labels, labels.shape)


features [[38 47 13]
 [10 39 41]
 [25  7 41]
 [25  7  6]
 [20 34 20]
 [42  0 21]
 [26 47 11]
 [41  3 16]
 [37 28 46]
 [37 45 41]] (10, 3)
labels [88 97 63 60 89 91 75 57 91 75] (10,)


In [19]:
# generate dataset
# then, slice as
#          features(except last column) and
#          labels (only last column)

dataset = np.random.default_rng(1).integers(low=0, high=100, size=(10, 4))

features = dataset[:, :-1]  #all rows, not last column
labels = dataset[:, -1]     #all rows, just last column

print("dataset", dataset, dataset.shape)      #dataset.size = n*m = 40
print("features", features, features.shape)   #dataset.size = n*m = 30
print("labels", labels, labels.shape)         #dataset.size = n*m = 10


dataset [[47 51 75 95]
 [ 3 14 82 94]
 [24 31 86 42]
 [27 82 25 40]
 [64 54  8  2]
 [86 75 83 53]
 [81 32 45 78]
 [12 30 12 45]
 [97 13 38 40]
 [90 20 50 26]] (10, 4)
features [[47 51 75]
 [ 3 14 82]
 [24 31 86]
 [27 82 25]
 [64 54  8]
 [86 75 83]
 [81 32 45]
 [12 30 12]
 [97 13 38]
 [90 20 50]] (10, 3)
labels [95 94 42 40  2 53 78 45 40 26] (10,)
