# sklearn - preprocessing general concepts

- scaler (standard or minmax) only scales (mostly moves) the dataset. Does not change the distribution!

In [1]:
from sklearn import preprocessing
import numpy as np

In [24]:
# dummy dataset

data = np.array(
    [
        [2.1, -1.9, 5.5],     #axis=1
        [-1.5, 2.4, 3.5],
        [0.5, -7.9, 5.6],
        [5.9, 2.3, -5.8]
    ])
       #axis=0

data.ndim, data.shape, data.size

(2, (4, 3), 12)

In [25]:
data.mean(), data.mean(axis=0), data.mean(axis=1)

(0.8916666666666666,
 array([ 1.75 , -1.275,  2.2  ]),
 array([ 1.9       ,  1.46666667, -0.6       ,  0.8       ]))

## standard scaler
μ = 0, σ = 1

In [36]:
# preprocessing.scale vs preprocessing.StandardScaler()
# latter is transform API, so it can be used pipelines!
# in pipelines, fit and transforms acs a little bit different for train and test data!!
#
# μ = 0, σ = 1

# scaledData = preprocessing.scale(X=data, axis=0)
scaler = preprocessing.StandardScaler()
scaledData = np.array(scaler.fit_transform(X= data))

scaledData.mean(axis=0), scaledData.std(axis=0)

(array([1.11022302e-16, 0.00000000e+00, 0.00000000e+00]), array([1., 1., 1.]))

## minmax scaler
min=0, max=1

In [38]:
# min=0, max=1

minmax_scaler = preprocessing.MinMaxScaler()
minMaxData = np.array(minmax_scaler.fit_transform(X=data))

print(minMaxData)

[[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


## normalization
