# sklearn - sk.datasets

- load sklearn data as pandas X and y, and
      - then combine X and y as dataframe
      - so you can to use both for EDA and inside sklearn functions

In [20]:
import sklearn as sk

# load_    to load sample data
# make_    to generate synthetic data
from sklearn.datasets import load_iris


In [22]:
# you can access sklearn dataset
# 1- as bunch type (default), then use .get("") method access as numpy array. splits X, y ...
# 2- as pandas dataframe and data and target dataframes

iris = load_iris()  # type(iris) => bunch data type

# so access data (numpy 2-d matrix), target (numpy 1-d array), feature_names, target_names..
print("features", iris.get("feature_names"),  # numpy 1-d array
      "\ndata", iris.get("data")[0:5])        # numpy 2-d array

features ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 
data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


## visualize