# sklearn - sk.datasets

- ..

In [4]:
import sklearn as sk
from sklearn.datasets import load_iris


In [18]:
iris = load_iris()  # type(iris) => bunch

# so access data (numpy 2-d matrix), target (numpy 1-d array), feature_names, target_names..
print("features", iris.get("feature_names"),
      "\ndata", iris.get("data")[0:5])

features ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 
data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
